name = "workers-for-platforms-example-project"
main = "src/index.ts"
compatibility_date = "2025-10-22"

[[ dispatch_namespaces ]]
binding = "dispatcher"
namespace = "workers-for-platforms-example-project"

[[ d1_databases ]]
binding = "worker_mappings"
database_name = "workers-for-platforms-example-project"
database_id = "placeholder-kv-id"
preview_database_id = "placeholder-preview-kv-id"

[var]
DISPATCH_NAMESPACE_ACCOUNT_ID = "binding" : "kv_binding"," id 
DISPATCH_NAMESPACE_AUTH_EMAIL = ""
# The necessary secrets are:
# - DISPATCH_NAMESPACE_AUTH_KEY
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
